<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxKNxjx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxKNxjx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxKNxjx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxKNxjx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZxKNxjx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZxKNxjx',
    'container.build_id' => 'd48b0f46',
    'container.build_time' => 1709717167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxKNxjx');
